### ISSUE TITLE
U2F token registration problem in Chrome

### ISSUE THREAD

**Issue by ondrokrc** [apowers313/fido2-server-demo#3]
I have a U2F Yubico key which I used successfully to Register and Login in Firefox 60 Beta.
The same process did not succeed in Chrome beta 67.0.3396.18 (see the screenshot).
After touching the blinking Yubikey and clicking Allow on the Chrome prompt, nothing else happens.

![fido2-u2f](https://user-images.githubusercontent.com/11937748/39355369-56906248-4a0d-11e8-8e3d-c9d7e278d1eb.png)

**Comment by apowers313** [comment]
Thanks for being my first bug submitter! :)

I've fixed a few bugs around this in the last week, and I think it should work now. Make sure you have the `chrome://flags` `#enable-experimental-web-platform-features` and `#enable-web-authentication-api` set.

Also, the error you see above mentions `the page does not have focus`. If you switch windows, tabs, or to the console window while performing a WebAuthn `create()` or `get()`, then Chrome will cancel the WebAuthn call (for security reasons).

**Comment by apowers313** [comment]
@ondrokrc can you confirm this is fixed?

**Comment by ondrokrc** [comment]
It works without problem now. Thanks.

**Comment by apowers313** [comment]
Thanks!
